### ISSUE TITLE
Unable to parse stylelint configuration "Undefined rule font-family-no-duplicate-names"

### ISSUE THREAD

**Issue by Jbz797** [stylelint/stylelint-config-standard#51] opened 2016-11-21 08:51 UTC
With version 15.0.0, i get this error "Undefined rule font-family-no-duplicate-names".

**My configuration:**
`
"stylelint": "^7.6.0",
"stylelint-config-standard": "^15.0.0"
`

**Comment by jeddy3** [comment] 2016-11-21 10:34
@Jbz797 Can you double check that your _local_ version of stylelint is actually `7.6.0` i.e.

```console
./node_modules/.bin/stylelint --version
```

The [tests are passing](https://travis-ci.org/stylelint/stylelint-config-standard/builds/177236022) and so I suspect stylelint wasn't correctly updated on your machine?

**Comment by Jbz797** [comment] 2016-11-21 10:38
![capture d ecran 2016-11-21 a 11 36 12](https://cloud.githubusercontent.com/assets/10371362/20479581/0fc43dae-afdf-11e6-9bec-ac5bad587b33.png)

**Comment by AntonNiklasson** [comment] 2016-11-21 11:00
Have you checked `which stylelint`?

**Comment by jeddy3** [comment] 2016-11-21 11:05
@Jbz797 Umm, curious. And what does the following display, if anything?

```
stylelint --version
```

**Comment by AntonNiklasson** [comment] 2016-11-21 11:09
I'm having the same issue, but only via [atom-linter-stylelint](https://github.com/AtomLinter/linter-stylelint).

Are you also using Atom?

**Comment by Jbz797** [comment] 2016-11-21 11:10
Yes I use "atom-linter-stylelint".

**Comment by AntonNiklasson** [comment] 2016-11-21 11:14
The issue is that `stylelint-config-standard` and `atom-linter-stylelint` depends on different version s of `stylelint`.

`font-family-no-duplicate-names` was added in the latest version of `stylelint`.

**Comment by AntonNiklasson** [comment] 2016-11-21 11:16
https://github.com/AtomLinter/linter-stylelint/issues/303

**Comment by jeddy3** [comment] 2016-11-21 11:20
@AntonNiklasson Thank you for open that issue. Closing this issue in favour of that one.

The `atom-linter-stylelint` guys are usually very good at putting out a new release quickly, as they use greenkeeper to notify them of new stylelint releases. However, it looks like greenkeeper didn't trigger a PR for `stylelint@7.6.0` and so they're probably unaware of the new release.

**Closed** 2016-11-21 11:21 UTC

**Comment by AntonNiklasson** [comment] 2016-11-21 12:59
I opened a PR, hopefully we get the fix soon :) https://github.com/AtomLinter/linter-stylelint/pull/304
